// form types
export const ADD_NAME = "ADD_NAME";
export const NAME_ERROR = "NAME_ERROR";
export const CLEAR_NAME_FIELD = "CLEAR_NAME_FIELD";
export const VALID_NAME_FIELD = "VALID_NAME_FIELD";

export const ADD_PHONENUMBER = "ADD_PHONENUMBER";
export const PHONENUMBER_ERROR = "PHONENUMBER_ERROR";
export const CLEAR_PHONENUMBER_FIELD = "CLEAR_PHONENUMBER_FIELD";
export const VALID_PHONENUMBER_FIELD = "VALID_PHONENUMBER_FIELD";

export const ADD_EMAIL = "ADD_EMAIL";
export const EMAIL_ERROR = "EMAIL_ERROR";
export const CLEAR_EMAIL_FIELD = "CLEAR_EMAIL_FIELD";
export const VALID_EMAIL_FIELD = "VALID_EMAIL_FIELD";

export const ADD_PASSWORD = "ADD_PASSWORD";
export const PASSWORD_ERROR = "PASSWORD_ERROR";
export const CLEAR_PASSWORD_FIELD = "CLEAR_PASSWORD_FIELD";
export const VALID_PASSWORD_FIELD = "VALID_PASSWORD_FIELD";

export const ADD_CONFIRM_PASSWORD = "ADD_CONFIRM_PASSWORD";
export const CONFIRM_PASSWORD_ERROR = "CONFIRM_PASSWORD_ERROR";
export const CLEAR_CONFIRMPASSWORD_FIELD = "CLEAR_CONFIRMPASSWORD_FIELD";
export const VALID_CONFIRMPASSWORD_FIELD = "VALID_CONFIRMPASSWORD_FIELD";

export const CLEAR_FIELDS = "CLEAR_FIELDS";
